title: Matt Malishev
author: darwinanddavis  
email: matthew.malishev@gmail.com
description: Data analysis and research projects meshing modelling and data viz for diverse problems

# show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: darwinanddavis
    pinterest: mmalishev
    linkedin: mmalishev
    twitter: darwinanddavis
    # instagram: darwinanddavis
    # googlescholar: user=m3MVeUMAAAAJ&hl=en  
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- spatial.md 
- disease.md 
- meta.md
- time_series.md
- coding_club.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag